# Generated by Django 3.2.4 on 2021-06-30 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('category_type', models.CharField(choices=[('D', 'Despesa'), ('R', 'Receita')], default='D', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='ReceiveBills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('status', models.CharField(choices=[('N', 'a Receber'), ('S', 'Recebido')], default='N', max_length=10)),
                ('receive_date', models.DateField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.category')),
            ],
        ),
        migrations.CreateModel(
            name='PayBills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('description', models.CharField(blank=True, max_length=250, null=True)),
                ('status', models.CharField(choices=[('N', 'a Pagar'), ('S', 'Pago')], default='N', max_length=10)),
                ('payment', models.CharField(choices=[('D', 'Dinheiro'), ('CD', 'Débito'), ('CC', 'Crédito'), ('B', 'Boleto')], default='D', max_length=10)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('pay_date', models.DateField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.category')),
            ],
        ),
    ]
