# Generated by Django 3.2.4 on 2021-06-19 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PayBills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('description', models.CharField(max_length=250)),
                ('due_day', models.DateTimeField(blank=True, null=True)),
                ('pay_day', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('P', 'Pago'), ('D', 'a Pagar')], default='D', max_length=10)),
            ],
        ),
    ]
